// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_GetPaymentDetailsProcedure : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE OR ALTER PROCEDURE dbo.GetPaymentDetails
                    @PaymentId UNIQUEIDENTIFIER
                AS
                BEGIN
                    SET NOCOUNT ON;

                    -- Empty guid mimics a payment that doesn't exist in the upstream system.
                    IF @PaymentId = '00000000-0000-0000-0000-000000000000'
                    BEGIN
                        RETURN;
                    END

                    DECLARE @Seed INT = ABS(CHECKSUM(CAST(@PaymentId AS NVARCHAR(36))));

                    SELECT
                        @PaymentId AS Id,
                        CASE @Seed % 5
                            WHEN 0 THEN N'Acme Corp'
                            WHEN 1 THEN N'Globex Inc'
                            WHEN 2 THEN N'Initech'
                            WHEN 3 THEN N'Umbrella LLC'
                            ELSE N'Stark Industries'
                        END AS Payee,
                        CAST((5000 + (@Seed % 995000)) AS DECIMAL(18, 2)) / 100.0 AS Amount,
                        CASE @Seed % 5
                            WHEN 0 THEN N'USD'
                            WHEN 1 THEN N'EUR'
                            WHEN 2 THEN N'GBP'
                            WHEN 3 THEN N'KES'
                            ELSE N'JPY'
                        END AS Currency,
                        CAST(DATEADD(DAY, -(@Seed % 30), CAST(GETUTCDATE() AS DATE)) AS DATETIME2) AS PaymentDate,
                        N'ACCT-' + RIGHT('0000000000' + CAST((@Seed / 7) % 1000000000 AS VARCHAR(10)), 10) AS BankAccount,
                        CASE @Seed % 5
                            WHEN 0 THEN N'Trade Payment'
                            WHEN 1 THEN N'Payroll'
                            WHEN 2 THEN N'Invoice Settlement'
                            WHEN 3 THEN N'Refund'
                            ELSE N'Intercompany Transfer'
                        END AS RemittanceClassification,
                        CASE @Seed % 5
                            WHEN 0 THEN N'SWIFT Network'
                            WHEN 1 THEN N'Visa Direct'
                            WHEN 2 THEN N'ACH Network'
                            WHEN 3 THEN N'SEPA'
                            ELSE N'Wire Transfer'
                        END AS PaymentPartner,
                        CASE @Seed % 2
                            WHEN 0 THEN N'Incoming'
                            ELSE N'Outgoing'
                        END AS Direction;
                END
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP PROCEDURE IF EXISTS dbo.GetPaymentDetails;");
        }
    }
}
